### ISSUE TITLE
Errors when running spaceX

### ISSUE THREAD

**Issue by jingeyu** [bayesrx/SpaceX#2]
when running spaceX, there is an error: Error in { : task 1 failed - "object 'alpha' not found" on my windows computer, R version 4.2.0. Could you please let me know if you have any suggestions? My R version is 4.2.0.

**Comment by Juliepvr** [comment]
I have the same issue, a window did open the first time I tried to run the example, about connecting to a server but I couldn't change the settings to allow it on my work computer

**Comment by HelloWorldLTY** [comment]
Hi all, I resolved this problem with the help of spacex's authors. They designed this tool based on R 4.1.2, and if we swithced R to this version, we can resolve this problem.

Moreover, the running time of this tool can be quite different based on the server or computer you have. I spent more than five hours to run example data based on my server.
